namespace: nennad
name: uptime_kuma
version: 1.2.0
readme: README.md
authors:
  - Nenad Gal <nennadgal@gmail.com>
description: This collection contains modules that allow to configure Uptime Kuma with Ansible. This is a fork of a repository made by Lucas Held
license_file: LICENSE
tags: [uptime_kuma]
repository: https://github.com/nennad/ansible-uptime-kuma
documentation: https://github.com/nennad/ansible-uptime-kuma/wiki
homepage: https://github.com/nennad/ansible-uptime-kuma
issues: https://github.com/nennad/ansible-uptime-kuma/issues
build_ignore:
  - '*/.pytest_cache'
  - .idea
  - build
  - scripts
  - run_tests.sh
  - build.sh
  - .gitignore
